flags: {}
packages:
- .
extra-deps:
- brick-0.47
- config-ini-0.2.4.0
- data-clist-0.1.2.2
- text-zipper-0.10.1
- word-wrap-0.4.1
- github: yes91/lambda-chat-protocol
  commit: a3e388d
resolver: lts-13.12
